# Generated by Django 5.0.1 on 2024-01-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='my_episodes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='my_rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movietype',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
